status = error

# Override on the command line, e.g. -Dblox.log.level=debug
rootLogger.level = ${sys:blox.log.level:-warn}
rootLogger.appenderRef.stdout.ref = stdout

appender.stdout.type = Console
appender.stdout.name = stdout
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.pattern = %5p [%t] (%F:%L) - %m%n
